print("Hello! 🎁")
print("I'm Adolfo I G. Esparas 🥶")
print("My course is BSCS")
print("Nice to meet you!😳")
print()

print("**********   *       *   **************   *        *    *******    *        *")
print("*        *    *     *          *          *        *   *       *   * *      *")
print("*        *     *   *           *          *        *   *       *   *  *     *")
print("**********      * *            *          **********   *       *   *   *    *")
print("*                *             *          *        *   *       *   *    *   *")
print("*                *             *          *        *   *       *   *     *  *")
print("*                *             *          *        *   *       *   *      * *")
print("*                *             *          *        *    *******    *        * 🐍")